### ISSUE TITLE
Clarify numbers on explorer landing page

### ISSUE THREAD

**Issue by LukasWallrich** [forrtproject/FReD#16]
@LukasRoeseler currently it is not clear how the numbers on the explorer landing page hang together - the 1338 selected studies should probably show up in the text as well? Can you clarify that?

**Comment by LukasRoeseler** [comment]
The 1338 are the validated & coded findings. If you uncheck "validated" and "coded", the number of selected findings equals. What is problematic is "X _of X_ studies selected" because here, the code cannot access the entire dataset.

- I removed the "of X" part.
- I replaced "studies" with "findings" so that it is correct and aligns with the description above.
